replicaCount: 1
image:
  repository: saksham1997/devops
  pullPolicy: Always
  tag: dev

resources:
  requests:
    cpu: "15m"
    memory: "15Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

targeCPUUtilizationPercentage: 80
targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
