apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-webapp.fullname" . }}
  labels:
    {{- include "devops-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "devops-webapp.selectorLabels" . | nindent 4 }}
